### ISSUE TITLE
Example spec should test dedicated example page

### ISSUE THREAD

**Issue by jplucinski** [Cognifide/cogE2E#3]
Created example scenarios should use dedicated example page. 

For example:
* [http://toolsqa.com/automation-practice-form/](http://toolsqa.com/automation-practice-form/)
* [https://www.ultimateqa.com/automation/](https://www.ultimateqa.com/automation/)
* [http://automationpractice.com/index.php](http://automationpractice.com/index.php)

**Comment by jplucinski** [comment]
Also:
* https://automationintesting.com/2018/10/introducing-automation-in-testing-online.html

**Comment by devzbysiu** [comment]
This project is going to be archived. Closing
