### ISSUE TITLE
Improve Puppeteer info in the README

### ISSUE THREAD

**Issue by mkmozgawa** [Cognifide/cogE2E#5]
1. Adding / configuring environments
In the readme it says

> Tests can be run on specific environment by running scripts like npm run test:prod. 

but there's no info where to find and modify the list of available environments (compare with the much more descriptive Protractor setup info).

2. Running test suites and excluding tests from running
The Protractor part includes info on how to run only certain test suites and/or how to exclude tests from running. It would be good to have this info readily available for Puppeteer as well.

**Comment by devzbysiu** [comment]
This project is going to be archived. Closing
