### ISSUE TITLE
Current setup doesn't work on case-sensitive file systems

### ISSUE THREAD

**Issue by mkmozgawa** [Cognifide/cogE2E#6]
If you try running the setup on a case-sensitive file system (hello, fellow Linux users!) you'll get the following error (this is for Protractor, but the same is true for Puppeteer):

`Could not read packageTemplate.json file in the ${tool} folder!
{ Error: ENOENT: no such file or directory, lstat '/home/user/npm/lib/node_modules/@cognifide/e2e/templates/Protractor'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/user/npm/lib/node_modules/@cognifide/e2e/templates/Protractor' }
`
This is caused by the fact that the Linux file system, unlike OS X and Windows, is case-sensitive. So the node modules installed for the user have the path ".../@cognifide/e2e/templates/protractor" and ".../@cognifide/e2e/templates/puppeteer", while the options in questions.js point to "Protractor" and "Puppeteer".

A quick workaround was to rename the dirs in my local node_modules but it would be cool to address this issue in the future by either changing the choices in questions.js to lowercase (seems a bit better) or renaming the template subfolders (clunky). This shouldn't break anything for all the other users but make our lives a bit easier :)

**Comment by adamkosmala** [comment]
Fixed in https://github.com/Cognifide/cogE2E/pull/8
